# Generated by Django 4.2.27 on 2026-06-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailedRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_delegation_name', models.CharField(max_length=255)),
                ('confirm_information', models.BooleanField(default=False)),
                ('agree_rules', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.country')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('badge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('t_shirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('food_type', models.CharField(blank=True, max_length=30, null=True)),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='uploads/team_leaders/passports/')),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='uploads/team_leaders/photos/')),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='uploads/team_leaders/consents/')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leaders', to='registration.detailedregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=70, null=True, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_number', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_students', models.PositiveIntegerField(default=0)),
                ('number_of_team_leaders', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_requests', to='registration.country')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_requests', to='registration.role')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_requests', to='registration.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('badge_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('competition_subject', models.CharField(default='Physics', max_length=50)),
                ('passport_number', models.CharField(max_length=50)),
                ('passport_expiry_date', models.DateField()),
                ('t_shirt_size', models.CharField(blank=True, max_length=10, null=True)),
                ('food_type', models.CharField(blank=True, max_length=30, null=True)),
                ('dietary_requirements', models.TextField(blank=True, null=True)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='uploads/contestants/passports/')),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='uploads/contestants/photos/')),
                ('commitment_form', models.FileField(blank=True, null=True, upload_to='uploads/contestants/commitments/')),
                ('consent_form', models.FileField(blank=True, null=True, upload_to='uploads/contestants/consents/')),
                ('parental_consent_form', models.FileField(blank=True, null=True, upload_to='uploads/contestants/consents/')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='registration.detailedregistration')),
            ],
        ),
    ]
