# Generated by Django 5.1.5 on 2026-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_delegation_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('validation', 'Validation error'), ('upload_limit', 'Total upload size limit'), ('malformed', 'Malformed form data'), ('server_error', 'Server error')], max_length=20)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('errors', models.JSONField(default=list)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('delegation_names', models.JSONField(default=list)),
                ('number_of_teams', models.CharField(blank=True, max_length=10)),
                ('uploads', models.JSONField(default=list)),
                ('total_upload_bytes', models.PositiveBigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
